# Generated by Django 5.0.3 on 2024-04-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('change_description_product', 'Change description'), ('change_categories_product', 'Change category'), ('change_publication_product', 'Change publication')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
